# Generated by Django 5.0.14 on 2025-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_university_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
