# Generated by Django 5.0.14 on 2026-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pushnotification_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
