# Generated by Django 6.0.1 on 2026-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_push_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('PAYPAL', 'PayPal')], default='MOBILE_MONEY', max_length=20),
        ),
    ]
