# Generated by Django 6.0.1 on 2026-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, default='', help_text='PayPal order ID for PayPal payments', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Savings Wallet'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYPAL', 'PayPal / Card')], default='WALLET', max_length=20),
        ),
    ]
