# Generated by Django 6.0.1 on 2026-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_paypal_to_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Savings Wallet'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYPAL', 'PayPal / Card'), ('COD', 'Cash on Delivery')], default='WALLET', max_length=20),
        ),
    ]
