# Generated by Django 6.0.1 on 2026-03-04 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_vendor_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_STATUS', 'Order Status Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('PRODUCT_REVIEW', 'Product Review')], default='NEW_ORDER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_notifications', to='shop.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_vendor_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
